#!/usr/bin/env python
"""Generate a markdown table listing every code cell in a notebook: its index,
cell id, nearest section heading, and a one-line preview. The index matches what
scripts/run_notebook_cells.py expects for --range / --cells.

Usage:
    python scripts/list_notebook_cells.py assets/earthquake_damage.ipynb NOTEBOOK_CELL_INDEX.md
"""
import sys

import nbformat


def first_line(source: str, limit: int = 70) -> str:
    for line in source.split("\n"):
        stripped = line.strip()
        if stripped:
            return stripped[:limit] + ("..." if len(stripped) > limit else "")
    return ""


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        raise SystemExit(1)

    nb_path = sys.argv[1]
    out_path = sys.argv[2] if len(sys.argv) > 2 else "NOTEBOOK_CELL_INDEX.md"

    nb = nbformat.read(nb_path, as_version=4)

    rows = []
    section = ""
    for i, cell in enumerate(nb.cells):
        if cell.cell_type == "markdown":
            src = "".join(cell.source).strip()
            first = src.split("\n")[0].strip()
            if first.startswith("#"):
                section = first.lstrip("#").strip()
        elif cell.cell_type == "code":
            preview = first_line("".join(cell.source))
            rows.append((i, cell.get("id", ""), section, preview))

    lines = [
        f"# Notebook Cell Index -- `{nb_path}`",
        "",
        f"Auto-generated by `scripts/list_notebook_cells.py`. Lists all {len(rows)} code cells "
        "with their 0-based index, id, section, and a preview of the first line of code.",
        "",
        "Use the `Index` column with `scripts/run_notebook_cells.py`, e.g.:",
        "```",
        "python scripts/run_notebook_cells.py " + nb_path + " --range 2 151",
        "python scripts/run_notebook_cells.py " + nb_path + " --cells 2-4,111",
        "```",
        "",
        "| Index | Cell ID | Section | Preview |",
        "|---|---|---|---|",
    ]
    for i, cid, sec, prev in rows:
        prev_escaped = prev.replace("|", "\\|")
        sec_escaped = sec.replace("|", "\\|")
        lines.append(f"| {i} | `{cid}` | {sec_escaped} | `{prev_escaped}` |")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {len(rows)} rows to {out_path}")


if __name__ == "__main__":
    main()
