#!/usr/bin/env python
"""Execute a range or explicit list of cells in a Jupyter notebook and write the
resulting outputs back into the same file, in place. Cells outside the selection
are left untouched.

Examples:
    # Run a contiguous range (inclusive), e.g. setup + EDA cells
    python scripts/run_notebook_cells.py assets/earthquake_damage.ipynb --range 2 151

    # Run an explicit set of indices / ranges, in the order given
    python scripts/run_notebook_cells.py assets/earthquake_damage.ipynb --cells 2-4,10,75-80

Cell indices are 0-based positions in the notebook's cell list (see
NOTEBOOK_CELL_INDEX.md, generated by scripts/list_notebook_cells.py, for a lookup
table). Since notebook cells typically depend on state built up by earlier cells
(imports, loaded dataframes, helper functions), a selection normally needs to
include whatever setup cells the target cell relies on.
"""
import argparse

import nbformat
from nbclient import NotebookClient


def parse_cells(spec: str, n_cells: int) -> list[int]:
    indices = []
    for part in spec.split(","):
        part = part.strip()
        if not part:
            continue
        if "-" in part:
            a, b = part.split("-")
            indices.extend(range(int(a), int(b) + 1))
        else:
            indices.append(int(part))
    for i in indices:
        if i < 0 or i >= n_cells:
            raise ValueError(f"Cell index {i} out of range (0-{n_cells - 1})")
    return indices


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("notebook", help="Path to the .ipynb file")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--range", nargs=2, type=int, metavar=("START", "END"),
                        help="Inclusive cell index range to execute, e.g. --range 2 151")
    group.add_argument("--cells", type=str,
                        help="Comma-separated cell indices/ranges, e.g. --cells 2-4,10,75-80")
    parser.add_argument("--kernel", default="python3", help="Kernel name (default: python3)")
    parser.add_argument("--timeout", type=int, default=1800, help="Per-cell timeout in seconds (default: 1800)")
    args = parser.parse_args()

    nb = nbformat.read(args.notebook, as_version=4)
    n_cells = len(nb.cells)

    if args.range:
        start, end = args.range
        indices = list(range(start, end + 1))
    else:
        indices = parse_cells(args.cells, n_cells)

    sub = nbformat.v4.new_notebook()
    sub.cells = [nb.cells[i] for i in indices]
    sub.metadata = nb.metadata

    print(f"Executing {len(indices)} cell(s): {indices}")
    client = NotebookClient(sub, timeout=args.timeout, kernel_name=args.kernel)
    client.execute()

    for pos, idx in enumerate(indices):
        nb.cells[idx] = sub.cells[pos]

    nbformat.write(nb, args.notebook)
    print(f"Done. Outputs for {len(indices)} cell(s) written back to {args.notebook}")


if __name__ == "__main__":
    main()
